import React from 'react'
import styles from './Bio.module.css'

function Bio(props) {
  let photoURL = "http://placekitten.com/56/56"

  return (
    <div className={`
      ${styles.Bio}
      ${props.className || ''}
    `}>
      <img src={photoURL} alt="Me" />
      <p>
        This is a blog generated by{' '}
        <a href="https://openai.com/">GPT-3</a>.
        <br />
        Please don't take this seriously.
      </p>
    </div>
  )
}

export default Bio
